### ISSUE TITLE
Dataset page revision

### ISSUE THREAD

**Issue by BastianGrahm** [tira-io/tira#169]
At branch `dataset-page-revision` I started reworking the dataset page so that it uses Vue to dynamically change the dataset and with it the shown leaderboard and runs.

A first commit was pushed where I:
  - introduced the Vue instance at [`tira-application/src/tira/static/tira/js/dataset_detail.js`](https://github.com/tira-io/tira/blob/dataset-page-revision/tira-application/src/tira/static/tira/js/dataset_detail.js) which is responsible for the dynamic change of the tables
  - reworked the template (currently at [`tira-application/src/tira/templates/tira/dataset_detail_new.html`](https://github.com/tira-io/tira/blob/dataset-page-revision/tira-application/src/tira/templates/tira/dataset_detail_new.html)

Mind the following:
  - The `.js` file is currently stored at [`tira-application/src/tira/static/tira/js/`](https://github.com/tira-io/tira/blob/dataset-page-revision/tira-application/src/tira/static/tira/js/) to make loading it via Disraptor easier. This can be moved in the future.
  - The delimiters for Vues template stuff are set to be `[[` and `]]` since we still use Django which renders its template using `{{` and `}}` already.

## TODOs:
  - [x] There is a problem regarding Djangos `url` template tag. It is used like so: https://github.com/tira-io/tira/blob/f2e44921bd3b07bc06f4c4a0f75cfdd2b889b343/tira-application/src/tira/templates/tira/dataset_detail_new.html#L123
Since with Vue the `vm` parameter changes dynamically the link cannot be rendered by Django as before, so the `url`-tag probably has to go. 

 - [x] The dropdown is rather experimental right now and should be redesigned. Mind this: https://vuejs.org/v2/guide/forms.html#example-5

  - [x] probably more of the site can be changed (e.g. dynamic loading of dataset list)

**Comment by BastianGrahm** [comment]
Pushed commit https://github.com/tira-io/tira/commit/f8ab1769fcd214576b8af0cb2ece3b3226fda0ed which removes the Django URL tags where sufficient. Also the runs table is now reworked and working.
