### ISSUE TITLE
testing TIRA in Feb/Mar 2022: procedure and docu FL

### ISSUE THREAD

**Issue by floebe** [tira-io/tira#188]
## resources
- easy access to VMs via groups ( top bar menu > `groups` ) :   &nbsp;  &nbsp;   https://www.tira.io/g
- remember previous hint on PAN baseline as testing material in
  https://github.com/tira-io/tira/issues/136#test-mat

## tasks
- [x] restore capability to access VM(s)
- [x] test whether VM [frank-loebe](https://www.tira.io/g/tira_vm_frank-loebe) at `betaweb121` runs, using [touche-task-1](https://www.tira.io/task/touche-task-1/)
  - [x] power on -> works, SSH port remains closed for ca. 1 min after state ´running´ and RDP port ´open´
- [ ] run first small tests (dummy runs)
  - [ ] single `echo test` command
    - [ ] via frank-loebe and using dataset `touche-task-1-2022-02-16`
      - state sequence: starting from `running` led to ´powering off´ > `sandboxing` (seems to take a while) > 
  - [ ] small script with variables and output testing

## observations
- in `software` section of a VM page (e.g. https://www.tira.io/task/touche-task-1/user/frank-loebe):
  - its confusing that `run` and `i` have text explanations when hovering over them, but the save and delete buttons do not

### issues filed
- #190

**Comment by MattiWe** [comment]
This is probably abandoned. Close.
