### ISSUE TITLE
Website Migration

### ISSUE THREAD

**Issue by MattiWe** [tira-io/tira#50]
This is the Meta-Achievement for the website migration. 
- [x] Run - review UI, see #87
- [x] Run - create new review, see #88
- [x] Run - run actions (unblind, delete, download)
- [x] VM - VM Info UI, see #89
- [x] VM - ajax (start, stop, shutdown)
- [x] VM - host grpc actions (vm_info, start, stop, shutdown)
- [x] VM - Frontend grpc actions (start, stop, shutdown) #90
- [x] Software - UI 
- [x] Software - ajax action (run, evaluate, abort)
- [x] Software - Frontend grpc actions (run, evaluate, abort)
- [x] Software -  host grpc actions (run, evaluate, abort)
